### ISSUE TITLE
Documentation isn't clear on difference between ValueType.Unknown and ValueType.Other

### ISSUE THREAD

**Issue by RPrimrose** [HotDocsCorp/hotdocs-open-sdk#21]
The ValueType enum has an "Unknown" value and a "Other" Value. The only place that "Other" is used is in the UnknownValue implementation of IValue. It's not clear what the difference is between these two values. Could documentation be added to the enum making clear the difference between them? Alternatively, could they be merged?

**Comment by lowellstewart** [comment]
I'm pretty sure there used to be a reason to have both of them, but that reason is no longer evident.

Just checked in a change to address this.  I merged them; ValueType.Unknown and ValueType.Other are now synonyms.  (That is, although they both still exist, they are equivalent.)  Possibly in the future we ought to remove ValueType.Other, as it is completely redundant. I left it in place in the unlikely event someone had referred to it in 3rd party code that uses the SDK.
